// frontend/src/constants/Actions.js
const Actions = {
  IO_INIT: "IO_INIT",
  SET_MESSAGES: "SET_MESSAGES",
  MORE_MESSAGES: "MORE_MESSAGES",
  MESSAGE: "MESSAGE",
  REMOVE_MESSAGE: "REMOVE_MESSAGE", // ✨ NEW ACTION
  MESSAGE_UPDATE: "MESSAGE_UPDATE", // ✨ ADD THIS

  SET_ROOM: "SET_ROOM",
  SET_ROOMS: "SET_ROOMS",
  ONLINE_USERS: "ONLINE_USERS",

  SET_EMOJI: "SET_EMOJIS",
  SET_TYPING: "SET_TYPING",
  SET_TYPING_USERS: "SET_TYPING_USERS",

  RTC_PRODUCER: "RTC_PRODUCER",
  RTC_PRODUCERS: "RTC_PRODUCERS",
  RTC_RESET_PRODUCERS: "RTC_RESET_PRODUCERS",
  RTC_LEAVE: "RTC_LEAVE",
  RTC_ROOM_ID: "RTC_ROOM_ID",
  RTC_CONSUMERS: "RTC_CONSUMERS",
  RTC_NEW_PEER: "RTC_NEW_PEER",
  RTC_CALL: "RTC_CALL",
  RTC_CLOSE: "RTC_CLOSE",
  RTC_ANSWER: "RTC_ANSWER",
  RTC_SET_COUNTERPART: "RTC_SET_COUNTERPART",

  // ── Phase 2: call lifecycle (driven by the server CallManager) ──
  RTC_CALL_STATE: "RTC_CALL_STATE", // local/explicit state transition or server snapshot
  RTC_CALL_ENDED: "RTC_CALL_ENDED", // whole call ended (carries reason)
  RTC_PEER_JOINED: "RTC_PEER_JOINED",
  RTC_PEER_LEFT: "RTC_PEER_LEFT",
  RTC_PEER_RECONNECTING: "RTC_PEER_RECONNECTING",
  RTC_PEER_RECONNECTED: "RTC_PEER_RECONNECTED",

  MESSAGES_ADD_ROOM_UNREAD: "MESSAGES_ADD_ROOM_UNREAD",
  MESSAGES_REMOVE_ROOM_UNREAD: "MESSAGES_REMOVE_ROOM_UNREAD",
  // REMOVED: CLEAR_UNREAD_STATE - no longer needed since we don't clear on logout

  // ✅ ADD THESE MISSING ACTIONS
  SYNC_UNREAD_STATE: "SYNC_UNREAD_STATE",
  SYNC_UNREAD_FROM_SERVER: "SYNC_UNREAD_FROM_SERVER",

  REFRESH_MEETINGS: "REFRESH_MEETINGS",
  MESSAGE_DELETED: "MESSAGE_DELETED",

  RTC_PRODUCER_PAUSED: "RTC_PRODUCER_PAUSED",
  RTC_PRODUCER_RESUMED: "RTC_PRODUCER_RESUMED",
};

export default Actions;
